sudo: required
language: generic


#tell travies we need a copy of docker running
services:
    - docker

#build our image using dockerfile.dev (since we want to run the test suite first)
before_install:
    - docker build -t ranger001/docker-client-test -f ./client/Dockerfile.dev ./client


#tell travis how to run our test suite for the build we just did 
script:
    - docker run -e CI=true ranger001/docker-client-test npm test -- --coverage

#build each of the containers
after_success:
    - docker build -t ranger001/multi-client ./client
    - docker build -t ranger001/multi-nginx ./nginx
    - docker build -t ranger001/multi-server ./server
    - docker build -t ranger001/multi-worker ./worker   
    #login to docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#tell travis how to deploy our code that we just built to docker hub
    - docker push ranger001/multi-client
    - docker push ranger001/multi-nginx
    - docker push ranger001/multi-server
    - docker push ranger001/multi-worker
    


